Make tests work with pytest 7.2.0 and without "py"
pytest no longer requires the "py" package, see
https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248
Because of this, tests would fail if "py" was not installed:
ModuleNotFoundError: No module named 'py.test'; 'py' is not a package

Bug: https://bugs.gentoo.org/888499